const APP_STATE_ACTION_TYPES = {
  SET_FORM: 'SET_FORM',
  RESET_FORM: 'RESET_FORM',
  FETCH_PREVIOUS_RESULT: 'FETCH_PREVIOUS_RESULT',
  RESET_FETCH_PREVIOUS_RESULT: 'RESET_FETCH_PREVIOUS_RESULT',
  UPDATE_DEVICE_WIDTH_HEIGHT: 'UPDATE_DEVICE_WIDTH_HEIGHT',
  FETCH_FAQ_DISCLAMER_SUCCESS: 'FETCH_FAQ_DISCLAMER_SUCCESS',
  SET_OTP_RESPONSE: 'SET_OTP_RESPONSE',
  RESET_OTP_RESPONSE: 'RESET_OTP_RESPONSE',
  UPDATE_OTP_RETRY_LIMIT: 'UPDATE_OTP_RETRY_LIMIT',
  RESET_OTP_RETRY_LIMIT: 'RESET_OTP_RETRY_LIMIT',
};

export default APP_STATE_ACTION_TYPES;
