const AUTH_ACTION_TYPES = {
  LOGIN_BY_CUST_ID_SUCCESS: 'LOGIN_BY_CUST_ID_SUCCESS',
  LOGIN_BY_MOBILE_PAN_DOB_SUCCESS: 'LOGIN_BY_MOBILE_PAN_DOB_SUCCESS',
  REG_AND_LOGIN_BY_MOBILE_SUCCESS: 'REG_AND_LOGIN_BY_MOBILE_SUCCESS',
  LOGIN_BY_MOBILE_OTP_SUCCESS: 'LOGIN_BY_MOBILE_OTP_SUCCESS',
  SET_LOGIN_BY_METHOD: 'SET_LOGIN_BY_METHOD',
  RESET_LOGIN_BY_METHOD: 'RESET_LOGIN_BY_METHOD',
  LOGOUT: 'LOGOUT',
};

export default AUTH_ACTION_TYPES;
