const DASHBOARD_ACTION_TYPES = {
  DASHBOARD_RESULT_SUCCESS: 'DASHBOARD_RESULT_SUCCESS',
  DASHBOARD_RESULT_FAILURE: 'DASHBOARD_RESULT_FAILURE',
  RESET_DASHBOARD_RESULT: 'RESET_DASHBOARD_RESULT',
};

export default DASHBOARD_ACTION_TYPES;
