const EMAIL_AND_DOWNLOAD_ACTION_TYPES = {
  FETCH_EMAIL_REPORT_SUCCESS: 'FETCH_EMAIL_REPORT_SUCCESS',
  FETCH_DOWNLOAD_REPORT_SUCCESS: 'FETCH_DOWNLOAD_REPORT_SUCCESS',
};

export default EMAIL_AND_DOWNLOAD_ACTION_TYPES;
